### ISSUE TITLE
not an issue/just a bit of discussion

### ISSUE THREAD

**Issue by PaulSoderlind** [johnmyleswhite/julia_tutorials#2]
Hi,

I took a quick look at your MLE tutorial. It looks nice. I just have one question and then a suggestion
1. why not `optimize(β -> -log_likelihood(X, y, β)...)`? Because you want to reuse the `nll`?
2. I have also [some tutorials on MLE](https://github.com/PaulSoderlind/FinancialEconometrics/blob/master/Ch12_MLE.ipynb) They include a simple example of both traditional and robust standard errors. Maybe of interest.

**Comment by johnmyleswhite** [comment]
1. Yes, I wanted to reuse `nll` in other places.
2. I'll add a pointer to your tutorial.

**Comment by PaulSoderlind** [comment]
Thanks,
I was merely suggesting to add something on the Hessian/gradients.   Best, Paul

**Comment by johnmyleswhite** [comment]
No worries: I think it's a great idea to link people to a discussion of robust standard errors.

**Comment by johnmyleswhite** [comment]
Closed by e8fc1168b295ed0543988f9855db278a32bd109f

**Comment by davidxiaoyuxu** [comment]
This tutorial looks nice!
I am running a MLE but the likelihood function is based on a numerical integration, so I don't have equations for Hessian. It would be great if there is an example like this case.

**Comment by johnmyleswhite** [comment]
Sounds like you need finite differences. Have you tried https://github.com/JuliaDiff/FiniteDiff.jl
